"""Native C signal V2 semantic contracts."""

from copy import deepcopy


V2_SIGNAL_CONTRACTS = {
    "v2_bottom_research": {
        "v2_signal": "C研",
        "v2_signal_name": "底部研究",
        "v2_state": "research_bottom",
        "v2_state_label": "底部观察",
        "v2_role": "watch",
        "v2_role_label": "观察",
        "v2_tone": "muted",
        "trade_intent": "watch_only",
        "trade_intent_label": "研究观察",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "invalid_condition_only",
        "v2_detail": "V2 事实层发现底部研究线索，只能进入观察，不生成交易计划。",
    },
    "v2_repair_watch": {
        "v2_signal": "C修",
        "v2_signal_name": "修复观察",
        "v2_state": "repair_setup",
        "v2_state_label": "修复观察",
        "v2_role": "watch",
        "v2_role_label": "观察",
        "v2_tone": "warning",
        "trade_intent": "watch_only",
        "trade_intent_label": "观察，不入场",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "invalid_condition_only",
        "v2_detail": "底背离后的修复事实只说明结构改善，必须等待 C回/C突/C爆 触发和 Plan Gate。",
    },
    "v2_bearish_new_low": {
        "v2_signal": "C研",
        "v2_signal_name": "阴包阳新低",
        "v2_state": "research_extreme",
        "v2_state_label": "极端观察",
        "v2_role": "watch",
        "v2_role_label": "观察",
        "v2_tone": "warning",
        "trade_intent": "watch_only",
        "trade_intent_label": "研究观察",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "invalid_condition_only",
        "v2_detail": "阴包阳创新低只作为极端观察事实，必须等待结构和触发确认。",
    },
    "v2_structure_candidate": {
        "v2_signal": "C候",
        "v2_signal_name": "结构候选",
        "v2_state": "structure_candidate",
        "v2_state_label": "结构候选",
        "v2_role": "candidate",
        "v2_role_label": "候选",
        "v2_tone": "muted",
        "trade_intent": "watch_only",
        "trade_intent_label": "候选观察",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "invalid_condition_only",
        "v2_detail": "分型、双底或矩形边界只是结构事实，仍需等待入场触发。",
    },
    "v2_attack_day": {
        "v2_signal": "C爆",
        "v2_signal_name": "攻击日",
        "v2_state": "attack_trigger",
        "v2_state_label": "攻击触发",
        "v2_role": "entry",
        "v2_role_label": "可交易",
        "v2_tone": "positive",
        "trade_intent": "attack_entry",
        "trade_intent_label": "攻击日计划校验",
        "requires_trade_plan": True,
        "requires_stop_loss": True,
        "v2_plan_scope": "entry_plan_required",
        "v2_detail": "攻击日只给触发事实，必须继续检查结构止损、追高风险和收益风险比。",
    },
    "v2_ignition": {
        "v2_signal": "C爆",
        "v2_signal_name": "起爆触发",
        "v2_state": "ignition_triggered",
        "v2_state_label": "起爆触发",
        "v2_role": "entry",
        "v2_role_label": "可交易",
        "v2_tone": "positive",
        "trade_intent": "ignition_entry",
        "trade_intent_label": "起爆计划校验",
        "requires_trade_plan": True,
        "requires_stop_loss": True,
        "v2_plan_scope": "entry_plan_required",
        "v2_detail": "起爆点触发后仍需交易计划拦截，不能直接等同于买入。",
    },
    "v2_bear_trap_recovery": {
        "v2_signal": "C突",
        "v2_signal_name": "破底翻突破",
        "v2_state": "bear_trap_breakout",
        "v2_state_label": "破底翻突破",
        "v2_role": "entry",
        "v2_role_label": "可交易",
        "v2_tone": "positive",
        "trade_intent": "breakout_entry",
        "trade_intent_label": "破底翻突破计划校验",
        "requires_trade_plan": True,
        "requires_stop_loss": True,
        "v2_plan_scope": "entry_plan_required",
        "v2_detail": "破底翻只说明洗盘后重新突破，仍需继续检查结构止损、目标价、2R 和宏观许可。",
    },
    "v2_breakout": {
        "v2_signal": "C突",
        "v2_signal_name": "突破入场",
        "v2_state": "entry_breakout",
        "v2_state_label": "突破可交易",
        "v2_role": "entry",
        "v2_role_label": "可交易",
        "v2_tone": "positive",
        "trade_intent": "breakout_entry",
        "trade_intent_label": "可按突破计划执行",
        "requires_trade_plan": True,
        "requires_stop_loss": True,
        "v2_plan_scope": "entry_plan_required",
        "v2_detail": "V2 矩形上沿或前高突破触发，仍需交易计划拦截追高与赔率。",
    },
    "v2_pullback": {
        "v2_signal": "C回",
        "v2_signal_name": "回踩入场",
        "v2_state": "entry_pullback",
        "v2_state_label": "回踩可交易",
        "v2_role": "entry",
        "v2_role_label": "可交易",
        "v2_tone": "positive",
        "trade_intent": "pullback_entry",
        "trade_intent_label": "可按回踩计划执行",
        "requires_trade_plan": True,
        "requires_stop_loss": True,
        "v2_plan_scope": "entry_plan_required",
        "v2_detail": "V2 回踩确认触发，仍需检查结构止损、收益风险比和仓位。",
    },
    "v2_risk_break": {
        "v2_signal": "C风",
        "v2_signal_name": "破位风控",
        "v2_state": "risk_break",
        "v2_state_label": "破位风险",
        "v2_role": "risk",
        "v2_role_label": "风控",
        "v2_tone": "danger",
        "trade_intent": "risk_control",
        "trade_intent_label": "检查持仓破位风险",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "risk_action",
        "v2_detail": "V2 独立风险事实判断为破位，优先处理仓位而不是新增入场。",
    },
    "v2_risk_heat": {
        "v2_signal": "C风",
        "v2_signal_name": "过热风控",
        "v2_state": "risk_heat",
        "v2_state_label": "过热风险",
        "v2_role": "risk",
        "v2_role_label": "风控",
        "v2_tone": "warning",
        "trade_intent": "risk_control",
        "trade_intent_label": "检查持仓过热风险",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "risk_action",
        "v2_detail": "V2 独立风险事实判断为过热，禁止追高并检查仓位。",
    },
    "v2_top_fractal_observe": {
        "v2_signal": "C研",
        "v2_signal_name": "顶分型观察",
        "v2_state": "observe_top_fractal",
        "v2_state_label": "顶部观察",
        "v2_role": "watch",
        "v2_role_label": "观察",
        "v2_tone": "warning",
        "trade_intent": "watch_only",
        "trade_intent_label": "观察阻力，不直接卖出",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "observation_only",
        "v2_detail": "顶分型只说明局部阻力或动能停顿，不能单独生成 S 点。",
    },
    "v2_top_fractal_risk": {
        "v2_signal": "C研",
        "v2_signal_name": "顶分型观察",
        "v2_state": "observe_top_fractal",
        "v2_state_label": "顶部观察",
        "v2_role": "watch",
        "v2_role_label": "观察",
        "v2_tone": "warning",
        "trade_intent": "watch_only",
        "trade_intent_label": "观察阻力，不直接卖出",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "observation_only",
        "v2_detail": "顶分型只说明局部阻力或动能停顿，不能单独生成 S 点。",
    },
    "v2_strong_resistance_scale_out": {
        "v2_signal": "C盈",
        "v2_signal_name": "强阻减仓",
        "v2_state": "scale_out_suggested",
        "v2_state_label": "减仓建议",
        "v2_role": "risk",
        "v2_role_label": "减仓",
        "v2_tone": "warning",
        "trade_intent": "scale_out",
        "trade_intent_label": "触强阻，考虑减仓",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "position_management",
        "v2_detail": "触及核心强阻只生成减仓或保护利润建议，不等同于清仓 S 点。",
    },
    "v2_exit_gate_sell": {
        "v2_signal": "C风",
        "v2_signal_name": "Exit Gate离场",
        "v2_state": "exit_gate_sell",
        "v2_state_label": "防守离场",
        "v2_role": "risk",
        "v2_role_label": "离场",
        "v2_tone": "danger",
        "trade_intent": "exit_position",
        "trade_intent_label": "执行防守离场",
        "requires_trade_plan": False,
        "requires_stop_loss": False,
        "v2_plan_scope": "exit_gate",
        "v2_detail": "动态防守线被跌破，Exit Gate 生成真正离场语义。",
    },
}

DEFAULT_V2_SIGNAL_CONTRACT = {
    "v2_signal": "C候",
    "v2_signal_name": "结构候选",
    "v2_state": "structure_candidate",
    "v2_state_label": "结构候选",
    "v2_role": "candidate",
    "v2_role_label": "候选",
    "v2_tone": "muted",
    "trade_intent": "watch_only",
    "trade_intent_label": "候选观察",
    "requires_trade_plan": False,
    "requires_stop_loss": False,
    "v2_plan_scope": "invalid_condition_only",
    "v2_detail": "该事件只作为结构证据进入候选，不直接生成交易动作。",
}

V2_CAMEL_KEYS = {
    "v2_signal": "v2Signal",
    "v2_signal_name": "v2SignalName",
    "v2_state": "v2State",
    "v2_state_label": "v2StateLabel",
    "v2_role": "v2Role",
    "v2_role_label": "v2RoleLabel",
    "v2_tone": "v2Tone",
    "trade_intent": "tradeIntent",
    "trade_intent_label": "tradeIntentLabel",
    "requires_trade_plan": "requiresTradePlan",
    "requires_stop_loss": "requiresStopLoss",
    "v2_plan_scope": "v2PlanScope",
    "v2_detail": "v2Detail",
}


def v2_signal_fields(event_key):
    """Return native V2 semantic fields."""
    return deepcopy(V2_SIGNAL_CONTRACTS.get(event_key, DEFAULT_V2_SIGNAL_CONTRACT))
